# Generated by Django 6.0.3 on 2026-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Решение проблемы'),
        ),
    ]
