# Generated by Django 6.0.3 on 2026-05-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_bids_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата взятия')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Примечание (например, для какой заявки)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.components', verbose_name='Комплектующее')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто взял')),
            ],
            options={
                'verbose_name': 'Транзакция комплектующего',
                'verbose_name_plural': 'Транзакции комплектующих',
            },
        ),
    ]
