# Generated by Django 6.0.3 on 2026-05-22 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0004_componenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия'),
        ),
        migrations.AddField(
            model_name='bids',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bids', to=settings.AUTH_USER_MODEL, verbose_name='Принял'),
        ),
        migrations.AddField(
            model_name='bids',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='bids',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_bids', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
    ]
