# Generated by Django 6.1a1 on 2026-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0005_bids_accepted_at_bids_accepted_by_bids_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='categories',
        ),
        migrations.AddField(
            model_name='components',
            name='devices',
            field=models.ManyToManyField(blank=True, to='uchet.devices', verbose_name='Устройства, в которых используется'),
        ),
        migrations.AddField(
            model_name='devices',
            name='year_started',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год начала работы'),
        ),
    ]
